module Proofs where

import Core

import System.IO

data Line = Line {
    lineNumber :: Int,
    lineContent :: Sentence,
    justification :: (String, Int, Int)
}

data Proof = Proof {
    proofName :: String, -- I don't NEED to add this (yet) technically. 
    proofGoal :: Sentence,
    proofLogic :: Logic,
    proofContent :: [Line]
}

lineToDatalog :: Proof -> Line -> String
lineToDatalog proof line = 
    let (justificationText, i, j) = justification line in
        "Line(" ++ show (lineNumber line) ++ ", " ++
        sentenceToDatalog (lineContent line) ++ ", " ++ 
        "\"" ++ justificationText ++ "\", " ++
        show i ++ ", " ++ 
        show j ++ ", " ++
        "$ToProve(" ++ sentenceToDatalog (proofGoal proof) ++ 
        -- (proofName proof) ++ -- would need more than just turning this on
        ")).\n"

proofToDatalog :: Proof -> String
proofToDatalog proof =
    "Claim($ToProve(" ++ 
    sentenceToDatalog (proofGoal proof) ++ 
    ")).\n\n" ++
    concatMap (lineToDatalog proof) (proofContent proof)
    
compileDatalogProof :: Proof -> IO ()
compileDatalogProof proof =
    withFile ("autogenerated_proofs/" ++ proofName proof ++ ".dl") WriteMode $ \h -> do
        hSetEncoding h utf8
        hPutStr h ("#include \"../datalog_engines/" ++ (logicName (proofLogic proof)) ++ ".dl\"\n\n")
        hPutStr h (proofToDatalog proof)

deductionAxiom1Schema :: Sentence
deductionAxiom1Schema = (OpNode impl [Atom "P", OpNode impl [Atom "Q", Atom "P"]])
deductionAxiom2Schema :: Sentence
deductionAxiom2Schema = (OpNode impl [OpNode impl [Atom "P", Atom "Q"], OpNode impl [OpNode impl [Atom "P", OpNode impl [Atom "Q", Atom "R"]], OpNode impl [Atom "P", Atom "R"]]])
matchesDeductionAxiom1 :: Axiom -> Bool
matchesDeductionAxiom1 axiom = haveSameStructure (axiomContent axiom) deductionAxiom1Schema
matchesDeductionAxiom2 :: Axiom -> Bool
matchesDeductionAxiom2 axiom = haveSameStructure (axiomContent axiom) deductionAxiom2Schema

deductionTransformation :: Logic -> Sentence -> Line -> [Line]
deductionTransformation logic hyp line =
    case justification line of
        ("Modus Ponens", ixp, ixpq) -> undefined
        ("Deduction", _, _) -> undefined
        (axnm, _, _) -> -- I think I do want to do it by what the thing says. or just assume it's an axiom
            
            undefined -- has to be an axiom. Ah, so I'm assuming that I'll do this step last, in case I want to add support for proofs. 