module Proofs where

import Core
import Specs

import Data.List
import System.IO

data Line = Line {
    lineNumber :: Int,
    lineContent :: Sentence,
    justification :: (String, Int, Int)
}

data Proof = Proof {
    proofName :: String, -- I don't NEED to add this (yet) technically. 
    proofGoal :: Sentence,
    proofLogic :: Logic,
    proofContent :: [Line]
}

lineToDatalog :: Proof -> Line -> String
lineToDatalog proof line = 
    let (justificationText, i, j) = justification line in
        "Line(" ++ show (lineNumber line) ++ ", " ++
        sentenceToDatalog (lineContent line) ++ ", " ++ 
        "\"" ++ justificationText ++ "\", " ++
        show i ++ ", " ++ 
        show j ++ ", " ++
        "$ToProve(" ++ sentenceToDatalog (proofGoal proof) ++ 
        -- (proofName proof) ++ -- would need more than just turning this on
        ")).\n"

proofToDatalog :: Proof -> String
proofToDatalog proof =
    "Claim($ToProve(" ++ 
    sentenceToDatalog (proofGoal proof) ++ 
    ")).\n\n" ++
    concatMap (lineToDatalog proof) (proofContent proof)
    
compileDatalogProof :: Proof -> IO ()
compileDatalogProof proof =
    withFile ("autogenerated_proofs/" ++ proofName proof ++ ".dl") WriteMode $ \h -> do
        hSetEncoding h utf8
        hPutStr h ("#include \"../datalog_engines/" ++ (logicName (proofLogic proof)) ++ ".dl\"\n\n")
        hPutStr h (proofToDatalog proof)

l1 = Line 1 (OpNode impl [OpNode impl [Atom "A", OpNode impl [Atom "A", Atom "A"]], OpNode impl [OpNode impl [Atom "A", OpNode impl [OpNode impl [Atom "A", Atom "A"], Atom "A"]], OpNode impl [Atom "A", Atom "A"]]]) ("Axiom3", 0, 0)
l2 = Line 2 (OpNode impl [Atom "A", OpNode impl [Atom "A", Atom "A"]]) ("Axiom2", 0, 0)
l3 = Line 3 (OpNode impl [OpNode impl [Atom "A", OpNode impl [OpNode impl [Atom "A", Atom "A"], Atom "A"]], OpNode impl [Atom "A", Atom "A"]]) ("Modus Ponens", 2, 1)
l4 = Line 4 (OpNode impl [Atom "A", OpNode impl [OpNode impl [Atom "A", Atom "A"], Atom "A"]]) ("Axiom2", 0, 0)
l5 = Line 5 (OpNode impl [Atom "A", Atom "A"]) ("Modus Ponens", 4, 3)

axiom1Proof = Proof "axiom1" (OpNode impl [Atom "A", Atom "A"]) (getLogic specIntuitionistic) [l1, l2, l3, l4, l5]

isInstance :: Logic -> Sentence -> Sentence -> Bool
-- the first Sentence is a sentence, second is a schema
-- need to think about naming for sentences/formulae
-- for now, assume everything is well-formed. 
isInstance logic sentence schema =
    case schema of
        Atom _ -> True
        OpNode schemaOp schemaArgs ->
            case sentence of
                Atom _ -> False
                OpNode sentOp sentArgs -> 
                    schemaOp == sentOp && all (\p -> isInstance logic (fst p) (snd p)) (zip sentArgs schemaArgs)

deductionTransformation :: Logic -> Sentence -> Line -> [Line]
deductionTransformation logic hyp line =
    case justification line of
        "Modus Ponens" ->
        "Deduction" -> undefined
        _ -> -- has to be an axiom. Ah, so I'm assuming that I'll do this step last, in case I want to add support for proofs. 