.type Sentence = Atom {name: symbol} | Conditional {s1: Sentence, s2: Sentence} | Bot {}

.decl Line(line_num: unsigned, line_content: Sentence, line_just: symbol, i: unsigned, j: unsigned)
.decl Justified(n: unsigned)
.decl Unjustified(n: unsigned)
.decl UnjustifiedCount(c: number)
.decl Goal(goal: Sentence)
.decl Proven(f: Sentence)

Unjustified(n) :- Line(n, _, _, _, _), !Justified(n).
UnjustifiedCount(c) :- c = count : { Unjustified(_) }.
Proven(f) :- Goal(f),
	Line(n, f, _, _, _),
	Justified(n),
	UnjustifiedCount(0).

.output Unjustified
.output Justified
.output Proven

Justified(n) :- Line(n, $Conditional(P, $Conditional(Q, P)), "Axiom2", _, _).
Justified(n) :- Line(n, $Conditional($Conditional(P, Q), $Conditional($Conditional(P, $Conditional(Q, R)), $Conditional(P, R))), "Axiom3", _, _).
Justified(n) :- Line(n, $Conditional($Conditional(P, $Bot()), $Conditional(P, Q)), "Axiom4", _, _).
Justified(n) :- Line(n, $Conditional($Conditional($Conditional(P, $Bot()), $Bot()), P), "Axiom5", _, _).
Justified(n) :- Line(n, Q, "Modus Ponens", i, j),
	i < n,
	Justified(i),
	Line(i, P, _, _, _),
	j < n,
	Justified(j),
	Line(j, $Conditional(P, Q), _, _, _).
