#include "../datalog_engines/intuitionistic.dl"

Claim($ToProve($Implication($Atom("A"), $Atom("A")))).

Line(1, $Implication($Implication($Atom("A"), $Implication($Atom("A"), $Atom("A"))), $Implication($Implication($Atom("A"), $Implication($Implication($Atom("A"), $Atom("A")), $Atom("A"))), $Implication($Atom("A"), $Atom("A")))), "Axiom3", 0, 0, $ToProve($Implication($Atom("A"), $Atom("A")))).
Line(2, $Implication($Atom("A"), $Implication($Atom("A"), $Atom("A"))), "Axiom2", 0, 0, $ToProve($Implication($Atom("A"), $Atom("A")))).
Line(3, $Implication($Implication($Atom("A"), $Implication($Implication($Atom("A"), $Atom("A")), $Atom("A"))), $Implication($Atom("A"), $Atom("A"))), "Modus Ponens", 2, 1, $ToProve($Implication($Atom("A"), $Atom("A")))).
Line(4, $Implication($Atom("A"), $Implication($Implication($Atom("A"), $Atom("A")), $Atom("A"))), "Axiom2", 0, 0, $ToProve($Implication($Atom("A"), $Atom("A")))).
Line(5, $Implication($Atom("A"), $Atom("A")), "Modus Ponens", 4, 3, $ToProve($Implication($Atom("A"), $Atom("A")))).
