#include "../../../datalog_engines/classical.dl"

Goal($Implication($Bot(), $Atom("A"))).

Line(1, $Implication($Bot(), $Bot()), "Axiom1", 0, 0).
Line(2, $Implication($Bot(), $Implication($Implication($Atom("A"), $Bot()), $Bot())), "Axiom2", 0, 0).
Line(3, $Implication($Implication($Bot(), $Implication($Implication($Atom("A"), $Bot()), $Bot())), $Implication($Bot(), $Implication($Bot(), $Implication($Implication($Atom("A"), $Bot()), $Bot())))), "Axiom2", 0, 0).
Line(4, $Implication($Bot(), $Implication($Bot(), $Implication($Implication($Atom("A"), $Bot()), $Bot()))), "Modus Ponens", 2, 3).
Line(5, $Implication($Implication($Bot(), $Bot()), $Implication($Implication($Bot(), $Implication($Bot(), $Implication($Implication($Atom("A"), $Bot()), $Bot()))), $Implication($Bot(), $Implication($Implication($Atom("A"), $Bot()), $Bot())))), "Axiom3", 0, 0).
Line(6, $Implication($Implication($Bot(), $Implication($Bot(), $Implication($Implication($Atom("A"), $Bot()), $Bot()))), $Implication($Bot(), $Implication($Implication($Atom("A"), $Bot()), $Bot()))), "Modus Ponens", 1, 5).
Line(7, $Implication($Bot(), $Implication($Implication($Atom("A"), $Bot()), $Bot())), "Modus Ponens", 4, 6).
Line(8, $Implication($Implication($Implication($Atom("A"), $Bot()), $Bot()), $Atom("A")), "Axiom5", 0, 0).
Line(9, $Implication($Implication($Implication($Implication($Atom("A"), $Bot()), $Bot()), $Atom("A")), $Implication($Bot(), $Implication($Implication($Implication($Atom("A"), $Bot()), $Bot()), $Atom("A")))), "Axiom2", 0, 0).
Line(10, $Implication($Bot(), $Implication($Implication($Implication($Atom("A"), $Bot()), $Bot()), $Atom("A"))), "Modus Ponens", 8, 9).
Line(11, $Implication($Implication($Bot(), $Implication($Implication($Atom("A"), $Bot()), $Bot())), $Implication($Implication($Bot(), $Implication($Implication($Implication($Atom("A"), $Bot()), $Bot()), $Atom("A"))), $Implication($Bot(), $Atom("A")))), "Axiom3", 0, 0).
Line(12, $Implication($Implication($Bot(), $Implication($Implication($Implication($Atom("A"), $Bot()), $Bot()), $Atom("A"))), $Implication($Bot(), $Atom("A"))), "Modus Ponens", 7, 11).
Line(13, $Implication($Bot(), $Atom("A")), "Modus Ponens", 10, 12).
