#include "../../../datalog_engines/classical_small.dl"

Goal($Conditional($Bot(), $Atom("A"))).

Line(1, $Conditional($Conditional($Bot(), $Conditional($Bot(), $Bot())), $Conditional($Conditional($Bot(), $Conditional($Conditional($Bot(), $Bot()), $Bot())), $Conditional($Bot(), $Bot()))), "Axiom3", 0, 0).
Line(2, $Conditional($Bot(), $Conditional($Bot(), $Bot())), "Axiom2", 0, 0).
Line(3, $Conditional($Conditional($Bot(), $Conditional($Conditional($Bot(), $Bot()), $Bot())), $Conditional($Bot(), $Bot())), "Modus Ponens", 2, 1).
Line(4, $Conditional($Bot(), $Conditional($Conditional($Bot(), $Bot()), $Bot())), "Axiom2", 0, 0).
Line(5, $Conditional($Bot(), $Bot()), "Modus Ponens", 4, 3).
Line(6, $Conditional($Bot(), $Conditional($Conditional($Atom("A"), $Bot()), $Bot())), "Axiom2", 0, 0).
Line(7, $Conditional($Conditional($Bot(), $Conditional($Conditional($Atom("A"), $Bot()), $Bot())), $Conditional($Bot(), $Conditional($Bot(), $Conditional($Conditional($Atom("A"), $Bot()), $Bot())))), "Axiom2", 0, 0).
Line(8, $Conditional($Bot(), $Conditional($Bot(), $Conditional($Conditional($Atom("A"), $Bot()), $Bot()))), "Modus Ponens", 6, 7).
Line(9, $Conditional($Conditional($Bot(), $Bot()), $Conditional($Conditional($Bot(), $Conditional($Bot(), $Conditional($Conditional($Atom("A"), $Bot()), $Bot()))), $Conditional($Bot(), $Conditional($Conditional($Atom("A"), $Bot()), $Bot())))), "Axiom3", 0, 0).
Line(10, $Conditional($Conditional($Bot(), $Conditional($Bot(), $Conditional($Conditional($Atom("A"), $Bot()), $Bot()))), $Conditional($Bot(), $Conditional($Conditional($Atom("A"), $Bot()), $Bot()))), "Modus Ponens", 5, 9).
Line(11, $Conditional($Bot(), $Conditional($Conditional($Atom("A"), $Bot()), $Bot())), "Modus Ponens", 8, 10).
Line(12, $Conditional($Conditional($Conditional($Atom("A"), $Bot()), $Bot()), $Atom("A")), "Axiom5", 0, 0).
Line(13, $Conditional($Conditional($Conditional($Conditional($Atom("A"), $Bot()), $Bot()), $Atom("A")), $Conditional($Bot(), $Conditional($Conditional($Conditional($Atom("A"), $Bot()), $Bot()), $Atom("A")))), "Axiom2", 0, 0).
Line(14, $Conditional($Bot(), $Conditional($Conditional($Conditional($Atom("A"), $Bot()), $Bot()), $Atom("A"))), "Modus Ponens", 12, 13).
Line(15, $Conditional($Conditional($Bot(), $Conditional($Conditional($Atom("A"), $Bot()), $Bot())), $Conditional($Conditional($Bot(), $Conditional($Conditional($Conditional($Atom("A"), $Bot()), $Bot()), $Atom("A"))), $Conditional($Bot(), $Atom("A")))), "Axiom3", 0, 0).
Line(16, $Conditional($Conditional($Bot(), $Conditional($Conditional($Conditional($Atom("A"), $Bot()), $Bot()), $Atom("A"))), $Conditional($Bot(), $Atom("A"))), "Modus Ponens", 11, 15).
Line(17, $Conditional($Bot(), $Atom("A")), "Modus Ponens", 14, 16).
